"""empty message

Revision ID: 71c223d90b51
Revises: a93e80732e9b
Create Date: 2018-11-16 10:54:32.719006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c223d90b51'
down_revision = 'a93e80732e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'timestamp')
    # ### end Alembic commands ###
